### PR TITLE
chore: add a ResponsiveTable with checkbox example

### PR DESCRIPTION
**Pull request by riccardo-forina**
**What this PR does / why we need it**:

Add an example for the `ResponsiveTable` where a checkbox column is used.

### CODE REVIEW

**Comment by HemaHG** [comment]
Thanks @riccardo-forina, it's really helpfull

**Comment by riccardo-forina** [comment]
Thinking more about it, don't do this. We need to natively support the checkbox in the responsive table so to handle the responsive part of the problem better.

The way it's done in the example I shared, the first column with content will be hidden if it gets small enough.

**Comment by suyash-naithani** [comment]
@riccardo-forina I am using something similar in acls table. I've wrapped my rows that I wrote in components in a <TableComposable> .
A challenge with that was getting the alignment of my table headers with the respective field for different resource types. 
Do you think it would be a good idea for me to use this component for the acls?

**Comment by riccardo-forina** [comment]
>Do you think it would be a good idea for me to use this component for the acls?

I'd say it's worth a try.

**Comment by HemaHG** [comment]
@riccardo-forina, I have 3 table components for consumers, so I have replaced the table with the responsive table, I have one question, how to apply sort for a particular column, I tried applying sort, but it's getting applied to all the columns

**Comment by suyash-naithani** [comment]
Could you rebase this PR with the latest changes?

**Comment by HemaHG** [comment]
created Jira https://issues.redhat.com/browse/MGDSTRM-8793

**Pull request closed without merging**
