### PR TITLE
feat: Add connectors card and service category label

### PR DESCRIPTION
**Pull request by srambach**
Adds a new connectors card to the overview page per https://issues.redhat.com/browse/MGDCTRS-645
Also adds service labels to all cards on the overview page.

### CODE REVIEW

**Review by riccardo-forina — APPROVED** [review]
Looks good to me!

**Review by jgiardino — APPROVED** [review]
LGTM! Thanks for making these updates!

**Comment by tiffanynolan** [comment]
@srambach Please update the product logo on the new RHOC card to be for Connectors instead of Data Science. There is a link to it in the copy doc. 

image

**Review by riccardo-forina — APPROVED** [review]
Good job with the image 👍

**Review by jgiardino — APPROVED** [review]
👍 Looks good with the new image :-)

**Comment by riccardo-forina** [comment]
Can we merge this?

**Pull request merged**
